language: php
php:
  - 7.2
env:
  - APP_ENV=development CC_TEST_REPORTER_ID=ab61a5c56b985202585f5eaaf424337c82776ba7bf6b66660ebbea55eeff13b5
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/phan-ast/build
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - touch .env
  - >-
    if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then echo 'date.timezone =
    Europe/Berlin' >> /etc/hhvm/php.ini; fi;
  - >-
    if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo 'date.timezone =
    Europe/Berlin' >> ~/.phpenv/versions/$(phpenv
    version-name)/etc/conf.d/travis.ini; fi;
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - ./tests/travis_setup.sh
  - mkdir /tmp/opcache || true; echo -e 'opcache.enable_cli=1\nopcache.file_cache=/tmp/opcache' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer validate
install:
  - composer --prefer-dist --classmap-authoritative install
script:
  - tests/run_all_tests
  - php internal/package.php
  - >-
    bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit; fi;'
  - >-
    bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi;'
after_script:
  - >-
    bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - >-
    bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'
  - >-
    bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
  - >-
    bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/test-reporter; fi;'
after_success:
  - travis_retry php vendor/bin/php-coveralls -v